name: create-release
on:
  workflow_run:
    workflows: ["run-tests"]
    types:
      - completed

jobs:
  github-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
        run: npx semantic-release -t '${version}' -b main
