on:
  push:
    tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - name: Run Tests
        run: npx ng test --browsers FirefoxHeadless --watch false
      - name: Build dist
        run: npx ng build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/
      - name: Create release on GitHub
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ./dist/
          name: "Nood ${{github.ref_name}}"
          generateReleaseNotes: true
          commit: "main"
          tag: ${{github.ref_name}}
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
