name: Create tag for new version
on:
  push:
    branches: [main]

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
        run: npx semantic-release -t ${version}


