name: publish-docker-image
on:
  push:
    tags:
      - "*"

jobs:
  docker-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Get all relevant tags
        uses: jupyterhub/action-major-minor-tag-calculator@v1
        id: gettags
        with:
          githubToken: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
          prefix: "${{secrets.DOCKER_USERNAME}}/nood:"
          branchRegex: "^[^/]+$"
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build, tag and push images
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ join(fromJson(steps.gettags.outputs.tags)) }}
